apiVersion: v1
kind: Pod
metadata:
  name: ngnix-pod
  labels: # Add your labels here, any key value pair can be added
    app: ngnix
    env: dev
spec:
  containers:
  - name: ngnix-container
    image: nginx:latest
    ports:
    - containerPort: 80 # Port on which the container will listen